[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_PUBLIC_SUPABASE_URL = "https://riopklhgkqmxtfgerpzu.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_johasJSDlQzmZldByHbCuA_5KE_m6vz"
