"use client"

import { useEffect, useMemo, useState } from "react"
import { useRouter } from "next/navigation"
import { getBrowserClient } from "@/lib/supabase/client"
import { Card, CardContent } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ArrowLeft, ChevronDown, ChevronUp, Search, Shirt } from "lucide-react"

type KitType = "Jogador" | "Goleiro"
type Kit = { id:string; kit_type:KitType; model_name:string; size:string; shirt_number:number; quantity:number; minimum_stock:number }
type Delivery = { uniform_kit_id:string; quantity:number }
const TYPES:KitType[]=["Jogador","Goleiro"]

export function UniformStock(){
 const router=useRouter(),supabase=useMemo(()=>getBrowserClient(),[])
 const [kits,setKits]=useState<Kit[]>([]),[deliveries,setDeliveries]=useState<Delivery[]>([]),[loading,setLoading]=useState(true)
 const [search,setSearch]=useState(""),[type,setType]=useState<"Todos"|KitType>("Todos"),[size,setSize]=useState("Todos"),[expanded,setExpanded]=useState<Record<string,boolean>>({})
 useEffect(()=>{void(async()=>{const[k,d]=await Promise.all([supabase.from("uniform_kits").select("*").order("kit_type").order("size").order("shirt_number"),supabase.from("uniform_deliveries").select("uniform_kit_id,quantity")]);setKits((k.data||[]) as Kit[]);setDeliveries((d.data||[]) as Delivery[]);setLoading(false)})()},[])
 const used=useMemo(()=>deliveries.reduce((m,d)=>{m[d.uniform_kit_id]=(m[d.uniform_kit_id]||0)+d.quantity;return m},{} as Record<string,number>),[deliveries])
 const available=(k:Kit)=>Math.max(0,k.quantity-(used[k.id]||0))
 const groups=useMemo(()=>{const m=new Map<string,Kit[]>();kits.forEach(k=>{const key=`${k.kit_type}||${k.model_name}||${k.size}`;m.set(key,[...(m.get(key)||[]),k])});return [...m.entries()].map(([id,items])=>({id,items,type:items[0].kit_type,model:items[0].model_name,size:items[0].size,minimum:Math.max(...items.map(k=>k.minimum_stock)),available:items.reduce((n,k)=>n+available(k),0)}))},[kits,used])
 const sizes=[...new Set(groups.map(g=>g.size))].sort((a,b)=>a.localeCompare(b,"pt-BR",{numeric:true}))
 const filtered=groups.filter(g=>(type==="Todos"||g.type===type)&&(size==="Todos"||g.size===size)&&`${g.type} ${g.model} ${g.size} ${g.items.map(k=>k.shirt_number).join(" ")}`.toLowerCase().includes(search.toLowerCase()))
 const total=groups.reduce((n,g)=>n+g.available,0)
 if(loading)return <div className="flex min-h-[50vh] items-center justify-center"><div className="h-10 w-10 animate-spin rounded-full border-4 border-primary/20 border-t-primary"/></div>
 return <div className="mx-auto w-full max-w-7xl space-y-6 pb-10">
  <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><Button variant="ghost" className="-ml-3 mb-2" onClick={()=>router.push("/uniforms")}><ArrowLeft className="mr-2 h-4 w-4"/>Voltar para Uniformes</Button><p className="text-sm font-semibold text-primary">Uniformes</p><h1 className="text-2xl font-bold sm:text-3xl">Consulta de estoque</h1><p className="mt-1 text-sm text-muted-foreground">Pesquise rapidamente por categoria, tamanho ou número da camisa.</p></div><div className="rounded-xl border bg-card px-5 py-3"><b className="text-2xl">{total}</b><span className="ml-2 text-sm text-muted-foreground">kits disponíveis</span></div></div>
  <Card><CardContent className="p-4 sm:p-5"><div className="grid gap-3 md:grid-cols-[1fr_190px_190px]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><Input className="h-11 pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ex.: nº 16, tamanho P, goleiro..."/></div><Select value={type} onValueChange={v=>setType(v as "Todos"|KitType)}><SelectTrigger className="h-11"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Todos">Todas categorias</SelectItem>{TYPES.map(t=><SelectItem key={t} value={t}>{t}</SelectItem>)}</SelectContent></Select><Select value={size} onValueChange={setSize}><SelectTrigger className="h-11"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Todos">Todos tamanhos</SelectItem>{sizes.map(s=><SelectItem key={s} value={s}>Tamanho {s}</SelectItem>)}</SelectContent></Select></div></CardContent></Card>
  <div className="grid gap-4">{filtered.length?filtered.map(g=>{const open=!!expanded[g.id],low=g.minimum>0&&g.available<g.minimum,sorted=[...g.items].sort((a,b)=>a.shirt_number-b.shirt_number);return <Card key={g.id} className={low?"border-amber-300":""}><button className="flex w-full flex-col gap-4 p-5 text-left sm:flex-row sm:items-center sm:justify-between" onClick={()=>setExpanded(x=>({...x,[g.id]:!x[g.id]}))}><div><div className="flex flex-wrap gap-2"><span className="rounded-lg bg-primary/10 px-3 py-1 text-xs font-bold text-primary">{g.type}</span><span className="rounded-lg border px-3 py-1 text-xs font-bold">TAMANHO {g.size}</span>{low&&<span className="rounded-lg bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">ESTOQUE BAIXO</span>}</div><div className="mt-3 flex flex-wrap gap-2">{sorted.map(k=><span key={k.id} className="rounded-lg bg-muted px-3 py-2 text-sm"><b>Nº {k.shirt_number}</b> · {available(k)} {available(k)===1?"kit":"kits"}</span>)}</div></div><div className="flex items-center gap-3"><div className="text-right"><p className="text-3xl font-black text-primary">{g.available}</p><p className="text-xs text-muted-foreground">disponíveis</p></div>{open?<ChevronUp className="h-5 w-5"/>:<ChevronDown className="h-5 w-5"/>}</div></button>{open&&<CardContent className="border-t bg-muted/20 p-5"><div className="mb-4 flex justify-between text-sm"><b>Detalhamento por número</b><span>Mínimo: <b>{g.minimum}</b></span></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{sorted.map(k=><div key={k.id} className="rounded-xl border bg-background p-4"><Shirt className="mb-2 h-5 w-5 text-primary"/><p className="text-xs text-muted-foreground">NÚMERO DA CAMISA</p><p className="text-2xl font-black">Nº {k.shirt_number}</p><p className="mt-3 border-t pt-3 text-sm"><b>{available(k)}</b> {available(k)===1?"kit disponível":"kits disponíveis"}</p></div>)}</div></CardContent>}</Card>}) : <div className="rounded-2xl border border-dashed py-14 text-center"><Search className="mx-auto mb-3 h-8 w-8 text-muted-foreground"/><p className="font-semibold">Nenhum uniforme encontrado</p><p className="text-sm text-muted-foreground">Altere a pesquisa ou os filtros.</p></div>}</div>
 </div>
}