begin;

create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'coach')),
  endpoint text not null unique,
  p256dh text not null,
  auth_key text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now()
);

create index if not exists idx_push_subscriptions_role on public.push_subscriptions(role);
create index if not exists idx_push_subscriptions_auth_user on public.push_subscriptions(auth_user_id);

alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from anon, authenticated;

create table if not exists public.push_notification_deliveries (
  id bigint generated by default as identity primary key,
  event_key text not null,
  subscription_id uuid not null references public.push_subscriptions(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('admin', 'coach')),
  title text not null,
  body text not null,
  href text not null default '/',
  created_at timestamptz not null default now(),
  sent_at timestamptz,
  claimed_at timestamptz,
  unique(event_key, subscription_id)
);

create index if not exists idx_push_deliveries_subscription_pending
  on public.push_notification_deliveries(subscription_id, created_at)
  where claimed_at is null;

alter table public.push_notification_deliveries enable row level security;
revoke all on public.push_notification_deliveries from anon, authenticated;

comment on table public.push_subscriptions is 'Web Push devices registered to authenticated SIGA users. Server/service-role access only.';
comment on table public.push_notification_deliveries is 'Idempotent queue/history for SIGA Web Push deliveries. Server/service-role access only.';

commit;
